baseURL = "https://othsueh.github.io/"
title = "Othsueh's Blog"
paginate = 5
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "G-W3RBT2SNTC"

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "ExampleSite"
description = "othsueh's blog, 大學生, 資工系, 程式, 讀書心得, othsue, oth"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = true
hidemeta = false
hideSummary = false
showtoc = true
tocopen = true
TocSide = 'left'
PygmentsCodeFences = true
PygmentsStyle = "vim"

  [params.assets]
  favicon = "<link / abs url>"
  favicon16x16 = "<link / abs url>"
  favicon32x32 = "<link / abs url>"
  apple_touch_icon = "<link / abs url>"
  safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "Othsueh's Blog"
  icon = "/apple-touch-icon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = true
  title = "Hello!🖖🏻"
  subtitle = "I'm Othsueh, a NTNU student major in CSIE, rookie in Computer Science, But I eager to Learn."
  imageUrl = "img/author.jpg"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "post"
    url = "post"

    [[params.profileMode.buttons]]
    name = "categories"
    url = "categories"

  [params.homeInfoParams]
  Title = "Hi there 👋"
  Content = "Welcome to my blog"

  [[params.socialIcons]]
  name = "stackoverflow"
  url = "https://stackoverflow.com/users/18195962/othsueh"

  [[params.socialIcons]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/chun-hsueh-yu-9537761b9/"
  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/othsueh"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = false
  hiddenInList = true
  hiddenInSingle = true


  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "search"
name = "search"
url = "/search/"
weight=10 

[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 20

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 30

[[menu.main]]
identifier = "archives"
name = "archives"
url = "/archives/"
weight = 40


[outputs]
home = [ "HTML", "RSS", "JSON" ]
