name = "Deploy Hugo site to Pages"

[on]
  [on.push]
  branches = [ "main" ]

[permissions]
contents = "read"
pages = "write"
id-token = "write"

[concurrency]
group = "pages"
cancel-in-progress = true

[defaults.run]
shell = "bash"

[jobs.build]
runs-on = "ubuntu-latest"

  [jobs.build.env]
  HUGO_VERSION = "0.108.0"

  [[jobs.build.steps]]
  name = "Install Hugo CLI"
  run = """
wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \\
&& sudo dpkg -i ${{ runner.temp }}/hugo.deb
"""

  [[jobs.build.steps]]
  name = "Install Dart Sass Embedded"
  run = "sudo snap install dart-sass-embedded"

  [[jobs.build.steps]]
  name = "Checkout"
  uses = "actions/checkout@v3"

    [jobs.build.steps.with]
    submodules = "recursive"

  [[jobs.build.steps]]
  name = "Setup Pages"
  id = "pages"
  uses = "actions/configure-pages@v2"

  [[jobs.build.steps]]
  name = "Install Node.js dependencies"
  run = "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"

  [[jobs.build.steps]]
  name = "Build with Hugo"
  run = """
hugo \\
  --minify \\
  --baseURL "${{ steps.pages.outputs.base_url }}/"
"""

    [jobs.build.steps.env]
    HUGO_ENVIRONMENT = "production"
    HUGO_ENV = "production"

  [[jobs.build.steps]]
  name = "Upload artifact"
  uses = "actions/upload-pages-artifact@v1"

    [jobs.build.steps.with]
    path = "./public"

[jobs.deploy]
runs-on = "ubuntu-latest"
needs = "build"

  [jobs.deploy.environment]
  name = "github-pages"
  url = "${{ steps.deployment.outputs.page_url }}"

  [[jobs.deploy.steps]]
  name = "Deploy to GitHub Pages"
  id = "deployment"
  uses = "actions/deploy-pages@v1"
